image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew

build_script:
<<<<<<< HEAD
  - ./gradlew test --info -Dselenide.headless=true
=======
  -Dselenide.headless=true
>>>>>>> 2c5aeb19eec8055cc5805dcdb1d3dd2408de7ef0
